### ISSUE TITLE
`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.` when trying to deploy new gem to production

### ISSUE THREAD

**Issue by David-Tamrazov** [jules2689/extended_bundler-errors#2]
Hello, I'm trying to deploy a commit that includes adding the Semian gem to the `Shopify/sell-on-amazon` app. However my builds on buildkite fail with this message:

```

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
--
  |  
  | current directory: /tmp/bundle/ruby/2.3.0/gems/semian-0.7.9/ext/semian
  | /usr/local/bin/ruby -r ./siteconf20180629-43-1jr9b64.rb extconf.rb
  | checking for openssl/sha.h... no
  | openssl is missing. please install openssl.
  | *** extconf.rb failed ***
  | Could not create Makefile due to some reason, probably lack of necessary
  | libraries and/or headers.  Check the mkmf.log file for more details.  You may
  | need configuration options.

```

At this point I'm blocked and not sure of how to proceed. Any guidance would be of great help and very appreciated 😄

**Comment by jules2689** [comment]
I've added handling for this and updated the plugin to v0.2.3
https://github.com/jules2689/extended_bundler-errors/commit/94912fe4cc08fe24cb86a73c493a225c8123491d

Thanks!
